// exerciseData.js
// All 9 exercise sets — 10 questions each

export const exerciseSets = {
  // ── DECIMALS ─────────────────────────────────────────────────────────────

  decimals_foundation: {
    id: "decimals_foundation",
    topic: "decimals",
    title: "Rounding to Decimal Places",
    difficulty: "foundation",
    difficultyLabel: "Foundation",
    icon: "fa-solid fa-percentage",
    accent: "#2563eb",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "Round 3.746 to 1 decimal place.",
        answer: "3.7",
        options: ["3.7", "3.8", "4.0"],
        hint: "Look at the 2nd decimal digit (4). It is in 0–4, so round down.",
      },
      {
        id: 2,
        text: "Round 8.352 to 1 decimal place.",
        answer: "8.4",
        options: ["8.3", "8.4", "8.5"],
        hint: "The 2nd decimal digit is 5. It is in 5–9, so round up.",
      },
      {
        id: 3,
        text: "Round 5.618 to 2 decimal places.",
        answer: "5.62",
        options: ["5.61", "5.62", "5.63"],
        hint: "Look at the 3rd decimal digit (8). Round up.",
      },
      {
        id: 4,
        text: "Round 12.045 to 2 decimal places.",
        answer: "12.05",
        options: ["12.04", "12.05", "12.06"],
        hint: "The 3rd decimal digit is 5. Round up the 4.",
      },
      {
        id: 5,
        text: "Round 0.8932 to 3 decimal places.",
        answer: "0.893",
        options: ["0.892", "0.893", "0.894"],
        hint: "The 4th decimal digit is 2. Round down.",
      },
      {
        id: 6,
        text: "Round 7.4996 to 3 decimal places.",
        answer: "7.500",
        options: ["7.499", "7.500", "7.501"],
        hint: "The 4th digit is 6. Round up the 9, which causes a chain.",
      },
      {
        id: 7,
        text: "Round 0.055 to 1 decimal place.",
        answer: "0.1",
        options: ["0.0", "0.1", "0.2"],
        hint: "The 2nd decimal digit is 5. Round up.",
      },
      {
        id: 8,
        text: "Round 99.995 to 2 decimal places.",
        answer: "100.00",
        options: ["99.99", "99.995", "100.00"],
        hint: "The 3rd digit is 5. Round up — chain rounding causes 99.99 → 100.00.",
      },
      {
        id: 9,
        text: "A length is measured as 4.673 m. Round to 2 d.p.",
        answer: "4.67",
        options: ["4.67", "4.68", "4.70"],
        hint: "The 3rd decimal digit is 3. Round down.",
      },
      {
        id: 10,
        text: "Round 2.449 to 1 decimal place.",
        answer: "2.4",
        options: ["2.4", "2.5", "3.0"],
        hint: "Only look at the 2nd decimal digit (4). It is 0–4, so round down.",
      },
    ],
  },

  decimals_higher: {
    id: "decimals_higher",
    topic: "decimals",
    title: "Significant Figures",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-percentage",
    accent: "#2563eb",
    xpPerQ: 3,
    questions: [
      {
        id: 1,
        text: "Round 4,820 to 1 significant figure.",
        answer: "5,000",
        options: ["4,000", "5,000", "4,800"],
        hint: "The first sig fig is 4. The next digit is 8 (≥5), so round up.",
      },
      {
        id: 2,
        text: "Round 0.00736 to 2 significant figures.",
        answer: "0.0074",
        options: ["0.0073", "0.0074", "0.0075"],
        hint: "Leading zeros are not sig figs. First sig fig is 7, second is 3. Next digit is 6 — round up.",
      },
      {
        id: 3,
        text: "Round 56,480 to 3 significant figures.",
        answer: "56,500",
        options: ["56,400", "56,500", "56,600"],
        hint: "First 3 sig figs are 5,6,4. Next digit is 8 — round up.",
      },
      {
        id: 4,
        text: "Round 0.05062 to 2 significant figures.",
        answer: "0.051",
        options: ["0.050", "0.051", "0.052"],
        hint: "First sig fig is 5, second is 0. Next digit is 6 — round up.",
      },
      {
        id: 5,
        text: "Round 3,995 to 3 significant figures.",
        answer: "4,000",
        options: ["3,990", "3,995", "4,000"],
        hint: "First 3 sig figs: 3,9,9. Next digit is 5 → rounds 9 up to 10, chain rounds up.",
      },
      {
        id: 6,
        text: "Round 0.19851 to 3 significant figures.",
        answer: "0.199",
        options: ["0.198", "0.199", "0.200"],
        hint: "First 3 sig figs: 1,9,8. Next digit is 5 — round up.",
      },
      {
        id: 7,
        text: "Round 70,450 to 2 significant figures.",
        answer: "70,000",
        options: ["70,000", "70,500", "71,000"],
        hint: "First 2 sig figs are 7,0. Next digit is 4 — round down.",
      },
      {
        id: 8,
        text: "A population of 238,600 — give to 2 sig figs.",
        answer: "240,000",
        options: ["230,000", "238,000", "240,000"],
        hint: "First 2 sig figs: 2,3. Next digit is 8 — round up.",
      },
      {
        id: 9,
        text: "Round 0.003049 to 2 significant figures.",
        answer: "0.0030",
        options: ["0.0030", "0.0031", "0.0029"],
        hint: "First sig fig is 3, second is 0. Next digit is 4 — round down.",
      },
      {
        id: 10,
        text: "Round 9.995 to 2 significant figures.",
        answer: "10",
        options: ["9.9", "10", "10.0"],
        hint: "First 2 sig figs: 9,9. Next digit is 5 — round up. Chain gives 10.",
      },
    ],
  },

  decimals_challenge: {
    id: "decimals_challenge",
    topic: "decimals",
    title: "Chain Rounding",
    difficulty: "challenge",
    difficultyLabel: "Challenge",
    icon: "fa-solid fa-percentage",
    accent: "#2563eb",
    xpPerQ: 4,
    questions: [
      {
        id: 1,
        text: "Round 4.45 to the nearest whole number.",
        answer: "4",
        options: ["4", "5", "6"],
        hint: "4.45 → look at 5 → round 4 up → 4.5 → look at 5 → round 4 up → 5. Wait — 4.45 rounds to 4 if you only round once from the 1st decimal place.",
      },
      {
        id: 2,
        text: "Round 2.449 to the nearest whole number.",
        answer: "2",
        options: ["2", "3", "4"],
        hint: "Look ONLY at the 1st decimal place (4). It is 0–4, so round down to 2.",
      },
      {
        id: 3,
        text: "Round 6.4499 to 1 decimal place.",
        answer: "6.4",
        options: ["6.4", "6.5", "7.0"],
        hint: "Look at 2nd decimal (4). Round down — no chain affects the 1 d.p. answer.",
      },
      {
        id: 4,
        text: "Round 3.9950 to 2 decimal places.",
        answer: "4.00",
        options: ["3.99", "4.00", "4.01"],
        hint: "3rd decimal is 5 → rounds 9 up → 4.00 via chain.",
      },
      {
        id: 5,
        text: "Round 7.4950 to 1 decimal place.",
        answer: "7.5",
        options: ["7.4", "7.5", "8.0"],
        hint: "Look at 2nd decimal (9). Round up to 7.5.",
      },
      {
        id: 6,
        text: "Round 0.9995 to 3 decimal places.",
        answer: "1.000",
        options: ["0.999", "1.000", "1.001"],
        hint: "4th decimal is 5 → chain rounds all the 9s up.",
      },
      {
        id: 7,
        text: "A runner clocks 12.449 seconds. Round to 1 d.p.",
        answer: "12.4",
        options: ["12.4", "12.5", "13.0"],
        hint: "Look only at the 2nd decimal (4). Round down.",
      },
      {
        id: 8,
        text: "Round 5.4545 to 1 decimal place.",
        answer: "5.5",
        options: ["5.4", "5.5", "6.0"],
        hint: "Look at 2nd decimal (5). Round up.",
      },
      {
        id: 9,
        text: "Round 1.0050 to 2 decimal places.",
        answer: "1.01",
        options: ["1.00", "1.01", "1.10"],
        hint: "3rd decimal is 5 → round the 0 up to 1.",
      },
      {
        id: 10,
        text: "Round 99.949 to 1 decimal place.",
        answer: "99.9",
        options: ["99.9", "100.0", "99.8"],
        hint: "Look at 2nd decimal (4). Round down.",
      },
    ],
  },

  // ── FACTORS ──────────────────────────────────────────────────────────────

  factors_foundation: {
    id: "factors_foundation",
    topic: "factors",
    title: "Finding All Factors",
    difficulty: "foundation",
    difficultyLabel: "Foundation",
    icon: "fa-solid fa-cubes",
    accent: "#7c3aed",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "How many factors does 12 have?",
        answer: "6",
        options: ["4", "6", "8"],
        hint: "Factors of 12: 1, 2, 3, 4, 6, 12 — that is 6 factors.",
      },
      {
        id: 2,
        text: "Which of these is NOT a factor of 18?",
        answer: "8",
        options: ["6", "8", "9"],
        hint: "18 ÷ 8 = 2.25 — not a whole number, so 8 is not a factor.",
      },
      {
        id: 3,
        text: "How many factors does 16 have?",
        answer: "5",
        options: ["4", "5", "6"],
        hint: "Factors: 1, 2, 4, 8, 16 — that is 5 factors.",
      },
      {
        id: 4,
        text: "What is the largest factor of 30 that is less than 30?",
        answer: "15",
        options: ["10", "15", "20"],
        hint: "30 ÷ 2 = 15. So 15 is the second-largest factor.",
      },
      {
        id: 5,
        text: "Which number has exactly 3 factors?",
        answer: "9",
        options: ["6", "9", "12"],
        hint: "Factors of 9: 1, 3, 9 — exactly 3. (Only perfect squares of primes have exactly 3 factors.)",
      },
      {
        id: 6,
        text: "How many factors does 24 have?",
        answer: "8",
        options: ["6", "8", "10"],
        hint: "Factors: 1, 2, 3, 4, 6, 8, 12, 24 — 8 factors.",
      },
      {
        id: 7,
        text: "Is 7 a factor of 56?",
        answer: "Yes",
        options: ["Yes", "No"],
        hint: "56 ÷ 7 = 8 exactly, so yes.",
      },
      {
        id: 8,
        text: "What is the sum of all factors of 10?",
        answer: "18",
        options: ["14", "18", "20"],
        hint: "Factors: 1 + 2 + 5 + 10 = 18.",
      },
      {
        id: 9,
        text: "Which of these numbers has the most factors: 6, 8, or 12?",
        answer: "12",
        options: ["6", "8", "12"],
        hint: "Factors of 6:4, of 8:4, of 12:6 — 12 wins.",
      },
      {
        id: 10,
        text: "How many factor pairs does 36 have?",
        answer: "5",
        options: ["4", "5", "6"],
        hint: "Pairs: (1,36)(2,18)(3,12)(4,9)(6,6) — 5 pairs.",
      },
    ],
  },

  factors_higher: {
    id: "factors_higher",
    topic: "factors",
    title: "Highest Common Factor",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-cubes",
    accent: "#7c3aed",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "Find the HCF of 12 and 18.",
        answer: "6",
        options: ["3", "6", "9"],
        hint: "Factors of 12: 1,2,3,4,6,12. Factors of 18: 1,2,3,6,9,18. Highest common = 6.",
      },
      {
        id: 2,
        text: "Find the HCF of 8 and 20.",
        answer: "4",
        options: ["2", "4", "8"],
        hint: "Factors of 8: 1,2,4,8. Factors of 20: 1,2,4,5,10,20. HCF = 4.",
      },
      {
        id: 3,
        text: "Find the HCF of 15 and 25.",
        answer: "5",
        options: ["3", "5", "15"],
        hint: "Factors of 15: 1,3,5,15. Factors of 25: 1,5,25. HCF = 5.",
      },
      {
        id: 4,
        text: "Find the HCF of 9 and 21.",
        answer: "3",
        options: ["3", "7", "9"],
        hint: "Factors of 9: 1,3,9. Factors of 21: 1,3,7,21. HCF = 3.",
      },
      {
        id: 5,
        text: "Find the HCF of 6 and 14.",
        answer: "2",
        options: ["2", "3", "6"],
        hint: "Factors of 6: 1,2,3,6. Factors of 14: 1,2,7,14. HCF = 2.",
      },
      {
        id: 6,
        text: "Find the HCF of 16 and 24.",
        answer: "8",
        options: ["4", "8", "16"],
        hint: "Factors of 16: 1,2,4,8,16. Factors of 24: 1,2,3,4,6,8,12,24. HCF = 8.",
      },
      {
        id: 7,
        text: "Find the HCF of 7 and 21.",
        answer: "7",
        options: ["1", "3", "7"],
        hint: "7 is prime. Its only factors are 1 and 7. 7 divides 21, so HCF = 7.",
      },
      {
        id: 8,
        text: "Find the HCF of 30 and 45.",
        answer: "15",
        options: ["5", "10", "15"],
        hint: "Factors of 30 include 15. 45 ÷ 15 = 3. So 15 is a common factor — and the highest.",
      },
      {
        id: 9,
        text: "Tiles measuring 18 cm and 24 cm — largest square tile that fits both?",
        answer: "6 cm",
        options: ["3 cm", "6 cm", "9 cm"],
        hint: "HCF(18, 24) = 6.",
      },
      {
        id: 10,
        text: "Find the HCF of 28 and 42.",
        answer: "14",
        options: ["7", "14", "21"],
        hint: "Factors of 28: 1,2,4,7,14,28. Factors of 42: 1,2,3,6,7,14,21,42. HCF = 14.",
      },
    ],
  },

  factors_challenge: {
    id: "factors_challenge",
    topic: "factors",
    title: "HCF with Larger Numbers",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-cubes",
    accent: "#7c3aed",
    xpPerQ: 3,
    questions: [
      {
        id: 1,
        text: "Find the HCF of 48 and 72.",
        answer: "24",
        options: ["12", "24", "36"],
        hint: "List factors of 48 and 72. Highest common is 24.",
      },
      {
        id: 2,
        text: "Find the HCF of 60 and 90.",
        answer: "30",
        options: ["15", "20", "30"],
        hint: "60 = 2×30, 90 = 3×30. HCF = 30.",
      },
      {
        id: 3,
        text: "Find the HCF of 84 and 56.",
        answer: "28",
        options: ["14", "28", "42"],
        hint: "84 = 3×28, 56 = 2×28. HCF = 28.",
      },
      {
        id: 4,
        text: "Find the HCF of 100 and 75.",
        answer: "25",
        options: ["5", "25", "50"],
        hint: "Factors of 75: 1,3,5,15,25,75. 100 ÷ 25 = 4. HCF = 25.",
      },
      {
        id: 5,
        text: "Find the HCF of 126 and 84.",
        answer: "42",
        options: ["14", "21", "42"],
        hint: "126 = 3×42, 84 = 2×42. HCF = 42.",
      },
      {
        id: 6,
        text: "Find the HCF of 120 and 180.",
        answer: "60",
        options: ["30", "60", "90"],
        hint: "120 = 2×60, 180 = 3×60. HCF = 60.",
      },
      {
        id: 7,
        text: "A rope 96 m and another 144 m — longest equal pieces with no waste?",
        answer: "48 m",
        options: ["24 m", "48 m", "96 m"],
        hint: "HCF(96, 144) = 48.",
      },
      {
        id: 8,
        text: "Find the HCF of 210 and 315.",
        answer: "105",
        options: ["35", "70", "105"],
        hint: "210 = 2×105, 315 = 3×105. HCF = 105.",
      },
      {
        id: 9,
        text: "Find the HCF of 144 and 108.",
        answer: "36",
        options: ["12", "36", "72"],
        hint: "144 = 4×36, 108 = 3×36. HCF = 36.",
      },
      {
        id: 10,
        text: "Find the HCF of 90, 60 and 45.",
        answer: "15",
        options: ["5", "10", "15"],
        hint: "HCF(90,60)=30, then HCF(30,45)=15.",
      },
    ],
  },

  // ── STANDARD FORM ────────────────────────────────────────────────────────

  standard_foundation: {
    id: "standard_foundation",
    topic: "standard",
    title: "Standard Form: Basics",
    difficulty: "foundation",
    difficultyLabel: "Foundation",
    icon: "fa-solid fa-superscript",
    accent: "#0d9488",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "What is 3 × 10² as an ordinary number?",
        answer: "300",
        options: ["30", "300", "3,000"],
        hint: "10² = 100. 3 × 100 = 300.",
      },
      {
        id: 2,
        text: "What is 7 × 10³ as an ordinary number?",
        answer: "7,000",
        options: ["700", "7,000", "70,000"],
        hint: "10³ = 1,000. 7 × 1,000 = 7,000.",
      },
      {
        id: 3,
        text: "What is 4 × 10¹ as an ordinary number?",
        answer: "40",
        options: ["4", "40", "400"],
        hint: "10¹ = 10. 4 × 10 = 40.",
      },
      {
        id: 4,
        text: "What is 9 × 10⁴ as an ordinary number?",
        answer: "90,000",
        options: ["9,000", "90,000", "900,000"],
        hint: "10⁴ = 10,000. 9 × 10,000 = 90,000.",
      },
      {
        id: 5,
        text: "Write 6,000 in standard form.",
        answer: "6 × 10³",
        options: ["6 × 10²", "6 × 10³", "6 × 10⁴"],
        hint: "6,000 = 6 × 1,000 = 6 × 10³.",
      },
      {
        id: 6,
        text: "Write 500 in standard form.",
        answer: "5 × 10²",
        options: ["5 × 10¹", "5 × 10²", "5 × 10³"],
        hint: "500 = 5 × 100 = 5 × 10².",
      },
      {
        id: 7,
        text: "What is 2 × 10⁵ as an ordinary number?",
        answer: "200,000",
        options: ["20,000", "200,000", "2,000,000"],
        hint: "10⁵ = 100,000. 2 × 100,000 = 200,000.",
      },
      {
        id: 8,
        text: "Which is largest: 3×10³, 4×10², or 9×10¹?",
        answer: "3 × 10³",
        options: ["3 × 10³", "4 × 10²", "9 × 10¹"],
        hint: "3,000 vs 400 vs 90. Largest is 3 × 10³.",
      },
      {
        id: 9,
        text: "Write 80 in standard form.",
        answer: "8 × 10¹",
        options: ["8 × 10⁰", "8 × 10¹", "8 × 10²"],
        hint: "80 = 8 × 10.",
      },
      {
        id: 10,
        text: "The distance to the moon is 384,000 km. Write in standard form (to 1 s.f.).",
        answer: "4 × 10⁵",
        options: ["3 × 10⁵", "4 × 10⁵", "3.84 × 10⁵"],
        hint: "To 1 s.f., 384,000 ≈ 400,000 = 4 × 10⁵.",
      },
    ],
  },

  standard_higher: {
    id: "standard_higher",
    topic: "standard",
    title: "Standard Form Calculations",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-superscript",
    accent: "#0d9488",
    xpPerQ: 3,
    questions: [
      {
        id: 1,
        text: "(3 × 10²) × (2 × 10³) = ?",
        answer: "6 × 10⁵",
        options: ["5 × 10⁵", "6 × 10⁵", "6 × 10⁶"],
        hint: "3×2=6, 10²×10³=10⁵. Answer: 6×10⁵.",
      },
      {
        id: 2,
        text: "(4 × 10⁴) ÷ (2 × 10²) = ?",
        answer: "2 × 10²",
        options: ["2 × 10¹", "2 × 10²", "2 × 10³"],
        hint: "4÷2=2, 10⁴÷10²=10². Answer: 2×10².",
      },
      {
        id: 3,
        text: "(5 × 10³) × (3 × 10²) = ?",
        answer: "1.5 × 10⁶",
        options: ["1.5 × 10⁵", "1.5 × 10⁶", "15 × 10⁵"],
        hint: "5×3=15=1.5×10¹, 10³×10²=10⁵. Total: 1.5×10⁶.",
      },
      {
        id: 4,
        text: "(8 × 10⁵) ÷ (4 × 10³) = ?",
        answer: "2 × 10²",
        options: ["2 × 10¹", "2 × 10²", "2 × 10³"],
        hint: "8÷4=2, 10⁵÷10³=10². Answer: 2×10².",
      },
      {
        id: 5,
        text: "(2 × 10³)² = ?",
        answer: "4 × 10⁶",
        options: ["4 × 10⁶", "4 × 10⁵", "2 × 10⁶"],
        hint: "2²=4, (10³)²=10⁶. Answer: 4×10⁶.",
      },
      {
        id: 6,
        text: "(6 × 10⁴) + (4 × 10⁴) = ?",
        answer: "1 × 10⁵",
        options: ["10 × 10⁴", "1 × 10⁵", "1.0 × 10⁴"],
        hint: "6+4=10, so 10×10⁴=1×10⁵.",
      },
      {
        id: 7,
        text: "(9 × 10³) − (3 × 10³) = ?",
        answer: "6 × 10³",
        options: ["6 × 10²", "6 × 10³", "6 × 10⁴"],
        hint: "9−3=6, same power: 6×10³.",
      },
      {
        id: 8,
        text: "Light travels 3×10⁸ m/s. How far in 5 seconds?",
        answer: "1.5 × 10⁹",
        options: ["1.5 × 10⁸", "1.5 × 10⁹", "3 × 10⁹"],
        hint: "3×10⁸ × 5 = 15×10⁸ = 1.5×10⁹.",
      },
      {
        id: 9,
        text: "(7 × 10⁶) ÷ (1 × 10²) = ?",
        answer: "7 × 10⁴",
        options: ["7 × 10³", "7 × 10⁴", "7 × 10⁵"],
        hint: "7÷1=7, 10⁶÷10²=10⁴.",
      },
      {
        id: 10,
        text: "(4 × 10³) × (4 × 10³) = ?",
        answer: "1.6 × 10⁷",
        options: ["1.6 × 10⁶", "1.6 × 10⁷", "16 × 10⁶"],
        hint: "4×4=16=1.6×10¹, 10³×10³=10⁶. Total: 1.6×10⁷.",
      },
    ],
  },

  standard_challenge: {
    id: "standard_challenge",
    topic: "standard",
    title: "Mixed Standard Form",
    difficulty: "challenge",
    difficultyLabel: "Challenge",
    icon: "fa-solid fa-superscript",
    accent: "#0d9488",
    xpPerQ: 5,
    questions: [
      {
        id: 1,
        text: "Put in order (smallest first): 4×10³, 2×10⁴, 8×10²",
        answer: "8×10², 4×10³, 2×10⁴",
        options: [
          "8×10², 4×10³, 2×10⁴",
          "4×10³, 8×10², 2×10⁴",
          "2×10⁴, 8×10², 4×10³",
        ],
        hint: "800, 4000, 20000 — smallest to largest.",
      },
      {
        id: 2,
        text: "(3×10⁵) × (2×10⁻²) = ? (express in standard form)",
        answer: "6 × 10³",
        options: ["6 × 10²", "6 × 10³", "6 × 10⁴"],
        hint: "3×2=6, 10⁵×10⁻²=10³.",
      },
      {
        id: 3,
        text: "A bacteria is 2×10⁻⁵ m wide. How many fit in 1×10⁻¹ m?",
        answer: "5,000",
        options: ["500", "5,000", "50,000"],
        hint: "(1×10⁻¹) ÷ (2×10⁻⁵) = 0.5×10⁴ = 5,000.",
      },
      {
        id: 4,
        text: "(1.5 × 10⁴) × (4 × 10³) = ?",
        answer: "6 × 10⁷",
        options: ["6 × 10⁶", "6 × 10⁷", "6 × 10⁸"],
        hint: "1.5×4=6, 10⁴×10³=10⁷.",
      },
      {
        id: 5,
        text: "Which is larger: 9.9×10⁴ or 1.1×10⁵?",
        answer: "1.1 × 10⁵",
        options: ["9.9 × 10⁴", "1.1 × 10⁵", "They are equal"],
        hint: "99,000 vs 110,000. 1.1×10⁵ is larger.",
      },
      {
        id: 6,
        text: "(5×10⁶) ÷ (2×10⁻¹) = ?",
        answer: "2.5 × 10⁷",
        options: ["2.5 × 10⁶", "2.5 × 10⁷", "2.5 × 10⁸"],
        hint: "5÷2=2.5, 10⁶÷10⁻¹=10⁷.",
      },
      {
        id: 7,
        text: "The mass of the Earth is 5.97×10²⁴ kg. Round to 1 s.f.",
        answer: "6 × 10²⁴",
        options: ["5 × 10²⁴", "6 × 10²⁴", "6 × 10²⁵"],
        hint: "The first sig fig is 5. Next digit is 9 → round up to 6.",
      },
      {
        id: 8,
        text: "(8 × 10⁴) + (2 × 10³) = ? (in standard form)",
        answer: "8.2 × 10⁴",
        options: ["8.2 × 10³", "8.2 × 10⁴", "10 × 10⁴"],
        hint: "80,000 + 2,000 = 82,000 = 8.2×10⁴.",
      },
      {
        id: 9,
        text: "√(4 × 10⁶) = ?",
        answer: "2 × 10³",
        options: ["2 × 10²", "2 × 10³", "4 × 10³"],
        hint: "√4=2, √(10⁶)=10³.",
      },
      {
        id: 10,
        text: "If 1 light-year ≈ 9.46×10¹⁵ m, how far is 3 light-years?",
        answer: "2.838 × 10¹⁶",
        options: ["2.838 × 10¹⁵", "2.838 × 10¹⁶", "28.38 × 10¹⁵"],
        hint: "3 × 9.46×10¹⁵ = 28.38×10¹⁵ = 2.838×10¹⁶.",
      },
    ],
  },
  // ── PERCENTAGES ──────────────────────────────────────────────────────────────

  percentages_foundation: {
    id: "percentages_foundation",
    topic: "percentages",
    title: "Percentages Basics",
    difficulty: "foundation",
    difficultyLabel: "Foundation",
    icon: "fa-solid fa-percent",
    accent: "#ef4444",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "What is 10% of 50?",
        answer: "5",
        options: ["5", "10", "15"],
        hint: "10% means divide by 10. 50 ÷ 10 = 5.",
      },
      {
        id: 2,
        text: "What is 25% of 20?",
        answer: "5",
        options: ["4", "5", "10"],
        hint: "25% is one quarter. A quarter of 20 is 5.",
      },
      {
        id: 3,
        text: "What is 50% of 36?",
        answer: "18",
        options: ["12", "18", "24"],
        hint: "50% means half. Half of 36 is 18.",
      },
      {
        id: 4,
        text: "What is 20% of 70?",
        answer: "14",
        options: ["7", "14", "21"],
        hint: "10% of 70 is 7, so 20% is 14.",
      },
      {
        id: 5,
        text: "Write 75% as a fraction.",
        answer: "3/4",
        options: ["1/2", "3/4", "4/5"],
        hint: "75% = 75/100 = 3/4.",
      },
      {
        id: 6,
        text: "Write 0.4 as a percentage.",
        answer: "40%",
        options: ["4%", "40%", "400%"],
        hint: "Multiply the decimal by 100. 0.4 × 100 = 40%.",
      },
      {
        id: 7,
        text: "What is 5% of 60?",
        answer: "3",
        options: ["3", "5", "6"],
        hint: "10% of 60 is 6, so 5% is half of that: 3.",
      },
      {
        id: 8,
        text: "What percentage is 15 out of 60?",
        answer: "25%",
        options: ["20%", "25%", "30%"],
        hint: "15/60 = 1/4 = 25%.",
      },
      {
        id: 9,
        text: "What is 1% of 200?",
        answer: "2",
        options: ["1", "2", "20"],
        hint: "1% means divide by 100. 200 ÷ 100 = 2.",
      },
      {
        id: 10,
        text: "A shirt costs £40. 50% off means the discount is?",
        answer: "£20",
        options: ["£10", "£20", "£30"],
        hint: "50% is half. Half of £40 is £20.",
      },
    ],
  },

  percentages_higher: {
    id: "percentages_higher",
    topic: "percentages",
    title: "Percentage Change",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-percent",
    accent: "#ef4444",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "Increase 80 by 10%.",
        answer: "88",
        options: ["88", "90", "96"],
        hint: "10% of 80 is 8, so 80 + 8 = 88.",
      },
      {
        id: 2,
        text: "Decrease 50 by 20%.",
        answer: "40",
        options: ["30", "40", "45"],
        hint: "20% of 50 is 10, so 50 - 10 = 40.",
      },
      {
        id: 3,
        text: "What is 15% of 120?",
        answer: "18",
        options: ["12", "18", "24"],
        hint: "10% is 12 and 5% is 6, so 15% is 18.",
      },
      {
        id: 4,
        text: "A £200 phone is reduced by 25%. New price?",
        answer: "£150",
        options: ["£140", "£150", "£175"],
        hint: "25% of £200 is £50. £200 - £50 = £150.",
      },
      {
        id: 5,
        text: "A number increases from 40 to 50. Percentage increase?",
        answer: "25%",
        options: ["20%", "25%", "30%"],
        hint: "Increase is 10. 10 ÷ 40 = 0.25 = 25%.",
      },
      {
        id: 6,
        text: "A number decreases from 90 to 72. Percentage decrease?",
        answer: "20%",
        options: ["10%", "20%", "25%"],
        hint: "Decrease is 18. 18 ÷ 90 = 0.2 = 20%.",
      },
      {
        id: 7,
        text: "Find 35% of 240.",
        answer: "84",
        options: ["72", "84", "96"],
        hint: "10% is 24, 30% is 72, and 5% is 12. Total = 84.",
      },
      {
        id: 8,
        text: "A price of £60 is increased by 15%. New price?",
        answer: "£69",
        options: ["£66", "£69", "£72"],
        hint: "15% of 60 is 9, so the new price is £69.",
      },
      {
        id: 9,
        text: "A coat costs £120 after a 20% discount. What was the original price?",
        answer: "£150",
        options: ["£140", "£150", "£160"],
        hint: "After 20% off, 80% remains. £120 ÷ 0.8 = £150.",
      },
      {
        id: 10,
        text: "Multiply 80 by 1.25.",
        answer: "100",
        options: ["90", "100", "110"],
        hint: "1.25 means 125%. 125% of 80 is 100.",
      },
    ],
  },

  percentages_challenge: {
    id: "percentages_challenge",
    topic: "percentages",
    title: "Percentages Problem Solving",
    difficulty: "challenge",
    difficultyLabel: "Challenge",
    icon: "fa-solid fa-percent",
    accent: "#ef4444",
    xpPerQ: 3,
    questions: [
      {
        id: 1,
        text: "A price increases from £80 to £92. What is the percentage increase?",
        answer: "15%",
        options: ["10%", "15%", "20%"],
        hint: "Increase is £12. £12 ÷ £80 = 0.15 = 15%.",
      },
      {
        id: 2,
        text: "A number is decreased by 30% to give 56. What was the original number?",
        answer: "80",
        options: ["70", "80", "90"],
        hint: "If 30% is removed, 70% remains. 56 ÷ 0.7 = 80.",
      },
      {
        id: 3,
        text: "After a 20% increase, a value becomes 144. Original value?",
        answer: "120",
        options: ["110", "120", "124"],
        hint: "120% = 1.2, so original = 144 ÷ 1.2 = 120.",
      },
      {
        id: 4,
        text: "A £500 bike is reduced by 10% and then by another 10%. Final price?",
        answer: "£405",
        options: ["£400", "£405", "£410"],
        hint: "First: £500 → £450. Then 10% off £450 is £45, so final price is £405.",
      },
      {
        id: 5,
        text: "What is the percentage profit if an item costs £40 and sells for £52?",
        answer: "30%",
        options: ["20%", "30%", "35%"],
        hint: "Profit is £12. £12 ÷ £40 = 0.3 = 30%.",
      },
      {
        id: 6,
        text: "What is the percentage loss if an item costs £75 and sells for £60?",
        answer: "20%",
        options: ["15%", "20%", "25%"],
        hint: "Loss is £15. £15 ÷ £75 = 0.2 = 20%.",
      },
      {
        id: 7,
        text: "A population of 2400 grows by 5%. New population?",
        answer: "2520",
        options: ["2500", "2520", "2640"],
        hint: "5% of 2400 is 120. 2400 + 120 = 2520.",
      },
      {
        id: 8,
        text: "A value is multiplied by 0.85. What percentage decrease is this?",
        answer: "15%",
        options: ["10%", "15%", "20%"],
        hint: "0.85 means 85% remains, so the decrease is 15%.",
      },
      {
        id: 9,
        text: "A jacket is reduced from £90 to £72. What percentage decrease is this?",
        answer: "20%",
        options: ["15%", "20%", "25%"],
        hint: "Decrease is £18. £18 ÷ £90 = 0.2 = 20%.",
      },
      {
        id: 10,
        text: "A £250 laptop has 12% VAT added. Total cost?",
        answer: "£280",
        options: ["£270", "£280", "£290"],
        hint: "12% of £250 is £30. Add this to £250 to get £280.",
      },
    ],
  },

  // ── RATIOS & SHARING ────────────────────────────────────────────────────────

  ratios_foundation: {
    id: "ratios_foundation",
    topic: "ratios",
    title: "Ratio Basics",
    difficulty: "foundation",
    difficultyLabel: "Foundation",
    icon: "fa-solid fa-scale-balanced",
    accent: "#d97706",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "Write the ratio of 2 red counters to 3 blue counters.",
        answer: "2:3",
        options: ["2:3", "3:2", "5:2"],
        hint: "Red : Blue = 2 : 3.",
      },
      {
        id: 2,
        text: "Simplify the ratio 4:8.",
        answer: "1:2",
        options: ["1:2", "2:4", "4:8"],
        hint: "Divide both parts by 4.",
      },
      {
        id: 3,
        text: "Simplify the ratio 6:9.",
        answer: "2:3",
        options: ["2:3", "3:2", "6:3"],
        hint: "Divide both parts by 3.",
      },
      {
        id: 4,
        text: "Share £12 in the ratio 1:2. What is the larger share?",
        answer: "£8",
        options: ["£4", "£6", "£8"],
        hint: "There are 3 parts total. £12 ÷ 3 = £4, so larger share is 2 parts = £8.",
      },
      {
        id: 5,
        text: "Share 15 sweets in the ratio 2:3. How many does the second person get?",
        answer: "9",
        options: ["6", "9", "12"],
        hint: "Total parts = 5. Each part = 3. Second person gets 3 × 3 = 9.",
      },
      {
        id: 6,
        text: "Which ratio is equivalent to 3:4?",
        answer: "6:8",
        options: ["6:8", "9:10", "12:20"],
        hint: "Multiply both parts of 3:4 by 2.",
      },
      {
        id: 7,
        text: "Simplify 10:15.",
        answer: "2:3",
        options: ["2:3", "5:3", "3:2"],
        hint: "Divide both parts by 5.",
      },
      {
        id: 8,
        text: "Share £20 in the ratio 1:4. What is the smaller share?",
        answer: "£4",
        options: ["£4", "£5", "£8"],
        hint: "Total parts = 5. Each part = £4.",
      },
      {
        id: 9,
        text: "The ratio of boys to girls is 3:5. Which is correct?",
        answer: "There are more girls than boys",
        options: [
          "There are more boys than girls",
          "There are more girls than boys",
          "There are equal numbers",
        ],
        hint: "5 is greater than 3, so there are more girls.",
      },
      {
        id: 10,
        text: "Simplify 12:18.",
        answer: "2:3",
        options: ["2:3", "3:2", "6:9"],
        hint: "Divide both by 6.",
      },
    ],
  },

  ratios_higher: {
    id: "ratios_higher",
    topic: "ratios",
    title: "Ratios & Sharing",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-scale-balanced",
    accent: "#d97706",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "Share £35 in the ratio 2:5. What is the larger share?",
        answer: "£25",
        options: ["£10", "£20", "£25"],
        hint: "Total parts = 7. Each part = £5. Larger share = 5 × £5 = £25.",
      },
      {
        id: 2,
        text: "The ratio of cats to dogs is 4:7. There are 28 dogs. How many cats are there?",
        answer: "16",
        options: ["12", "16", "20"],
        hint: "7 parts = 28, so 1 part = 4. Cats = 4 × 4 = 16.",
      },
      {
        id: 3,
        text: "Simplify 18:24.",
        answer: "3:4",
        options: ["3:4", "4:3", "6:8"],
        hint: "Divide both parts by 6.",
      },
      {
        id: 4,
        text: "Share 42 in the ratio 4:3. What does the first part get?",
        answer: "24",
        options: ["18", "21", "24"],
        hint: "Total parts = 7. Each part = 6. First gets 4 × 6 = 24.",
      },
      {
        id: 5,
        text: "A drink is mixed in the ratio juice:water = 1:3. How much water is needed for 5 litres of juice?",
        answer: "15 litres",
        options: ["10 litres", "15 litres", "20 litres"],
        hint: "Water is 3 times the juice. 5 × 3 = 15 litres.",
      },
      {
        id: 6,
        text: "The ratio of red to blue beads is 5:2. There are 21 beads in total. How many are red?",
        answer: "15",
        options: ["6", "15", "18"],
        hint: "Total parts = 7. Each part = 3. Red = 5 × 3 = 15.",
      },
      {
        id: 7,
        text: "Simplify 21:14.",
        answer: "3:2",
        options: ["2:3", "3:2", "7:4"],
        hint: "Divide both by 7.",
      },
      {
        id: 8,
        text: "Share £54 in the ratio 4:5. What is the second share?",
        answer: "£30",
        options: ["£24", "£27", "£30"],
        hint: "Total parts = 9. Each part = £6. Second share = 5 × £6 = £30.",
      },
      {
        id: 9,
        text: "Flour and sugar are in the ratio 3:2. If there are 18 cups of flour, how much sugar is needed?",
        answer: "12 cups",
        options: ["9 cups", "12 cups", "15 cups"],
        hint: "3 parts = 18, so 1 part = 6. Sugar = 2 parts = 12 cups.",
      },
      {
        id: 10,
        text: "The ratio 8:12 simplifies to?",
        answer: "2:3",
        options: ["2:3", "3:2", "4:6"],
        hint: "Divide both numbers by 4.",
      },
    ],
  },

  ratios_challenge: {
    id: "ratios_challenge",
    topic: "ratios",
    title: "Ratio Problem Solving",
    difficulty: "challenge",
    difficultyLabel: "Challenge",
    icon: "fa-solid fa-scale-balanced",
    accent: "#d97706",
    xpPerQ: 3,
    questions: [
      {
        id: 1,
        text: "Share £84 in the ratio 3:4. What is the first share?",
        answer: "£36",
        options: ["£24", "£36", "£48"],
        hint: "Total parts = 7. Each part = £12. First share = 3 × £12 = £36.",
      },
      {
        id: 2,
        text: "The ratio of boys:girls is 5:7. There are 60 students altogether. How many are girls?",
        answer: "35",
        options: ["25", "30", "35"],
        hint: "Total parts = 12. Each part = 5. Girls = 7 × 5 = 35.",
      },
      {
        id: 3,
        text: "A recipe uses sugar and flour in the ratio 2:5. If 300 g of flour is used, how much sugar is needed?",
        answer: "120 g",
        options: ["100 g", "120 g", "150 g"],
        hint: "5 parts = 300 g, so 1 part = 60 g. Sugar = 2 parts = 120 g.",
      },
      {
        id: 4,
        text: "The ratio of red:blue:green pens is 2:3:5. There are 50 pens. How many are green?",
        answer: "25",
        options: ["10", "15", "25"],
        hint: "Total parts = 10. Each part = 5. Green = 5 × 5 = 25.",
      },
      {
        id: 5,
        text: "£72 is shared between A and B in the ratio 5:7. How much does B get?",
        answer: "£42",
        options: ["£30", "£35", "£42"],
        hint: "Total parts = 12. Each part = £6. B gets 7 × £6 = £42.",
      },
      {
        id: 6,
        text: "Orange and black counters are in the ratio 4:9. There are 52 counters. How many are black?",
        answer: "36",
        options: ["16", "28", "36"],
        hint: "Total parts = 13. Each part = 4. Black = 9 × 4 = 36.",
      },
      {
        id: 7,
        text: "A map uses the scale 1:20000. 1 cm on the map represents how many metres in real life?",
        answer: "200 m",
        options: ["20 m", "200 m", "2000 m"],
        hint: "20000 cm = 200 m.",
      },
      {
        id: 8,
        text: "The ratio of adults to children is 7:3. If there are 18 children, how many adults are there?",
        answer: "42",
        options: ["36", "42", "49"],
        hint: "3 parts = 18, so 1 part = 6. Adults = 7 × 6 = 42.",
      },
      {
        id: 9,
        text: "A class has boys and girls in the ratio 4:5. If there are 36 learners, how many are boys?",
        answer: "16",
        options: ["16", "18", "20"],
        hint: "Total parts = 9. Each part = 4. Boys = 4 × 4 = 16.",
      },
      {
        id: 10,
        text: "Red:white paint is mixed in the ratio 3:7. If 21 litres of red paint are used, how much white paint is needed?",
        answer: "49 litres",
        options: ["42 litres", "49 litres", "63 litres"],
        hint: "3 parts = 21 litres, so 1 part = 7 litres. White = 7 parts = 49 litres.",
      },
    ],
  },

  // ── DIRECT & INVERSE PROPORTION ─────────────────────────────────────────────

  proportion_foundation: {
    id: "proportion_foundation",
    topic: "proportion",
    title: "Direct Proportion Basics",
    difficulty: "foundation",
    difficultyLabel: "Foundation",
    icon: "fa-solid fa-up-down-left-right",
    accent: "#8b5cf6",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "If 1 pen costs £2, how much do 3 pens cost?",
        answer: "£6",
        options: ["£5", "£6", "£8"],
        hint: "3 pens cost 3 × £2 = £6.",
      },
      {
        id: 2,
        text: "If 4 apples cost £8, how much do 2 apples cost?",
        answer: "£4",
        options: ["£2", "£4", "£6"],
        hint: "1 apple costs £2, so 2 apples cost £4.",
      },
      {
        id: 3,
        text: "5 books weigh 10 kg. How much do 10 books weigh?",
        answer: "20 kg",
        options: ["15 kg", "20 kg", "25 kg"],
        hint: "If the number doubles, the weight doubles.",
      },
      {
        id: 4,
        text: "A car travels 60 miles in 2 hours at constant speed. How far in 1 hour?",
        answer: "30 miles",
        options: ["20 miles", "30 miles", "40 miles"],
        hint: "Half the time means half the distance.",
      },
      {
        id: 5,
        text: "If 3 pencils cost 90p, how much do 6 pencils cost?",
        answer: "£1.80",
        options: ["£1.20", "£1.50", "£1.80"],
        hint: "6 is double 3, so the cost doubles too.",
      },
      {
        id: 6,
        text: "If y is directly proportional to x, what happens to y when x doubles?",
        answer: "It doubles",
        options: ["It halves", "It doubles", "It stays the same"],
        hint: "In direct proportion, both change by the same scale factor.",
      },
      {
        id: 7,
        text: "2 kg of rice costs £3. How much does 6 kg cost?",
        answer: "£9",
        options: ["£6", "£9", "£12"],
        hint: "6 kg is 3 times as much, so the cost is 3 times as much.",
      },
      {
        id: 8,
        text: "A worker earns £40 for 5 hours. How much for 10 hours?",
        answer: "£80",
        options: ["£60", "£80", "£100"],
        hint: "10 hours is double 5 hours, so earnings double.",
      },
      {
        id: 9,
        text: "7 identical packs contain 21 biscuits. How many biscuits in 1 pack?",
        answer: "3",
        options: ["2", "3", "4"],
        hint: "21 ÷ 7 = 3.",
      },
      {
        id: 10,
        text: "If 8 metres of ribbon cost £12, how much do 4 metres cost?",
        answer: "£6",
        options: ["£4", "£6", "£8"],
        hint: "4 metres is half of 8 metres, so the cost is half.",
      },
    ],
  },

  proportion_higher: {
    id: "proportion_higher",
    topic: "proportion",
    title: "Direct & Inverse Proportion",
    difficulty: "higher",
    difficultyLabel: "Higher",
    icon: "fa-solid fa-up-down-left-right",
    accent: "#8b5cf6",
    xpPerQ: 2,
    questions: [
      {
        id: 1,
        text: "If 5 workers take 12 hours to do a job, how long do 10 workers take?",
        answer: "6 hours",
        options: ["6 hours", "10 hours", "24 hours"],
        hint: "More workers means less time. Doubling workers halves the time.",
      },
      {
        id: 2,
        text: "If y is inversely proportional to x, what happens to y when x doubles?",
        answer: "It halves",
        options: ["It doubles", "It halves", "It stays the same"],
        hint: "Inverse proportion means one goes up while the other goes down.",
      },
      {
        id: 3,
        text: "3 machines make 24 toys in an hour. How many toys do 6 machines make?",
        answer: "48",
        options: ["36", "48", "54"],
        hint: "Direct proportion: doubling machines doubles output.",
      },
      {
        id: 4,
        text: "A journey takes 4 hours at 60 mph. How long would it take at 120 mph?",
        answer: "2 hours",
        options: ["2 hours", "3 hours", "8 hours"],
        hint: "Doubling speed halves the time.",
      },
      {
        id: 5,
        text: "If 8 taps fill a pool in 6 hours, how long would 4 taps take?",
        answer: "12 hours",
        options: ["3 hours", "6 hours", "12 hours"],
        hint: "Halving the number of taps doubles the time.",
      },
      {
        id: 6,
        text: "y is directly proportional to x. If x = 4 and y = 20, find y when x = 6.",
        answer: "30",
        options: ["24", "30", "36"],
        hint: "Scale factor from 4 to 6 is ×1.5, so y also ×1.5.",
      },
      {
        id: 7,
        text: "If 2 kg of bananas cost £3.20, what do 7 kg cost?",
        answer: "£11.20",
        options: ["£9.60", "£11.20", "£12.80"],
        hint: "1 kg costs £1.60, so 7 kg costs £11.20.",
      },
      {
        id: 8,
        text: "6 people can paint a fence in 15 hours. How long for 3 people?",
        answer: "30 hours",
        options: ["20 hours", "30 hours", "45 hours"],
        hint: "Half the people means double the time.",
      },
      {
        id: 9,
        text: "If x and y are directly proportional, and x triples, what happens to y?",
        answer: "It triples",
        options: ["It triples", "It halves", "It stays the same"],
        hint: "Direct proportion means same multiplier.",
      },
      {
        id: 10,
        text: "If 12 workers take 5 days, how many days would 20 workers take?",
        answer: "3 days",
        options: ["2 days", "3 days", "4 days"],
        hint: "Use inverse proportion. 12 × 5 = 60 worker-days. 60 ÷ 20 = 3 days.",
      },
    ],
  },

  proportion_challenge: {
    id: "proportion_challenge",
    topic: "proportion",
    title: "Proportion Problem Solving",
    difficulty: "challenge",
    difficultyLabel: "Challenge",
    icon: "fa-solid fa-up-down-left-right",
    accent: "#8b5cf6",
    xpPerQ: 3,
    questions: [
      {
        id: 1,
        text: "8 workers can build a wall in 15 days. How many days would 12 workers take?",
        answer: "10 days",
        options: ["8 days", "10 days", "12 days"],
        hint: "Total work = 8 × 15 = 120 worker-days. 120 ÷ 12 = 10 days.",
      },
      {
        id: 2,
        text: "If y is directly proportional to x and y = 18 when x = 6, find y when x = 10.",
        answer: "30",
        options: ["24", "30", "36"],
        hint: "18 ÷ 6 = 3, so y = 3x. When x = 10, y = 30.",
      },
      {
        id: 3,
        text: "A car travels 150 miles in 3 hours. At the same speed, how far in 7 hours?",
        answer: "350 miles",
        options: ["300 miles", "350 miles", "375 miles"],
        hint: "150 ÷ 3 = 50 mph. In 7 hours, distance = 50 × 7 = 350.",
      },
      {
        id: 4,
        text: "10 pipes fill a tank in 4 hours. How long would 16 pipes take?",
        answer: "2.5 hours",
        options: ["2 hours", "2.5 hours", "3 hours"],
        hint: "10 × 4 = 40 pipe-hours. 40 ÷ 16 = 2.5 hours.",
      },
      {
        id: 5,
        text: "If 7 notebooks cost £11.90, what do 15 notebooks cost?",
        answer: "£25.50",
        options: ["£24.50", "£25.50", "£26.50"],
        hint: "One notebook costs £11.90 ÷ 7 = £1.70. Then multiply by 15.",
      },
      {
        id: 6,
        text: "y is inversely proportional to x. If y = 12 when x = 2, find y when x = 8.",
        answer: "3",
        options: ["2", "3", "6"],
        hint: "For inverse proportion, x × y stays constant. 2 × 12 = 24. Then 24 ÷ 8 = 3.",
      },
      {
        id: 7,
        text: "4 people can pack 180 boxes in a day. How many boxes can 10 people pack in a day?",
        answer: "450",
        options: ["360", "450", "540"],
        hint: "Direct proportion: 180 ÷ 4 = 45 per person-group part, then ×10 = 450.",
      },
      {
        id: 8,
        text: "A map has scale 1:50000. A distance of 3 cm on the map represents how many kilometres?",
        answer: "1.5 km",
        options: ["0.5 km", "1.5 km", "15 km"],
        hint: "3 × 50000 = 150000 cm = 1500 m = 1.5 km.",
      },
      {
        id: 9,
        text: "If 9 machines make 630 parts in 7 hours, how many parts do 3 machines make in 7 hours?",
        answer: "210",
        options: ["180", "210", "240"],
        hint: "3 machines is one third of 9 machines, so output is one third of 630.",
      },
      {
        id: 10,
        text: "A recipe for 8 people needs 600 g of rice. How much rice is needed for 14 people?",
        answer: "1050 g",
        options: ["900 g", "1000 g", "1050 g"],
        hint: "Direct proportion: 600 ÷ 8 = 75 g per person. 75 × 14 = 1050 g.",
      },
    ],
  },
};
